/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using chemApiClient.Client;
using chemApiClient.Api;
using chemApiClient.Model;

namespace chemApiClient.Test
{
    /// <summary>
    ///  Class for testing SubstancesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SubstancesApiTests
    {
        private SubstancesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SubstancesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubstancesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SubstancesApi
            //Assert.IsInstanceOfType(typeof(SubstancesApi), instance, "instance is a SubstancesApi");
        }

        
        /// <summary>
        /// Test GetRelatedSubstances
        /// </summary>
        [Test]
        public void GetRelatedSubstancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetRelatedSubstances(substanceId, appKey, appId);
            //Assert.IsInstanceOf<RelatedSubstances> (response, "response is RelatedSubstances");
        }
        
        /// <summary>
        /// Test GetSubstance
        /// </summary>
        [Test]
        public void GetSubstanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstance(substanceId, appKey, appId);
            //Assert.IsInstanceOf<Substance> (response, "response is Substance");
        }
        
        /// <summary>
        /// Test GetSubstanceIdentifiers
        /// </summary>
        [Test]
        public void GetSubstanceIdentifiersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstanceIdentifiers(substanceId, appKey, appId);
            //Assert.IsInstanceOf<Identifiers> (response, "response is Identifiers");
        }
        
        /// <summary>
        /// Test GetSubstanceInventoryHits
        /// </summary>
        [Test]
        public void GetSubstanceInventoryHitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstanceInventoryHits(substanceId, appKey, appId);
            //Assert.IsInstanceOf<Inventories> (response, "response is Inventories");
        }
        
        /// <summary>
        /// Test GetSubstanceListHits
        /// </summary>
        [Test]
        public void GetSubstanceListHitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //int? limit = null;
            //int? offset = null;
            //string q = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstanceListHits(substanceId, limit, offset, q, appKey, appId);
            //Assert.IsInstanceOf<RegulatoryLists> (response, "response is RegulatoryLists");
        }
        
        /// <summary>
        /// Test GetSubstanceNames
        /// </summary>
        [Test]
        public void GetSubstanceNamesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string substanceId = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstanceNames(substanceId, appKey, appId);
            //Assert.IsInstanceOf<SubstanceNames> (response, "response is SubstanceNames");
        }
        
        /// <summary>
        /// Test GetSubstances
        /// </summary>
        [Test]
        public void GetSubstancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //string q = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetSubstances(limit, offset, q, appKey, appId);
            //Assert.IsInstanceOf<Substances> (response, "response is Substances");
        }
        
    }

}
