/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using chemApiClient.Client;
using chemApiClient.Api;
using chemApiClient.Model;

namespace chemApiClient.Test
{
    /// <summary>
    ///  Class for testing UpdatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UpdatesApiTests
    {
        private UpdatesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UpdatesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdatesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UpdatesApi
            //Assert.IsInstanceOfType(typeof(UpdatesApi), instance, "instance is a UpdatesApi");
        }

        
        /// <summary>
        /// Test GetEntryUpdate
        /// </summary>
        [Test]
        public void GetEntryUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string releaseId = null;
            //string substanceId = null;
            //int? limit = null;
            //int? offset = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetEntryUpdate(releaseId, substanceId, limit, offset, appKey, appId);
            //Assert.IsInstanceOf<EntryChanges> (response, "response is EntryChanges");
        }
        
        /// <summary>
        /// Test GetListUpdates
        /// </summary>
        [Test]
        public void GetListUpdatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string releaseId = null;
            //int? limit = null;
            //int? offset = null;
            //string appKey = null;
            //string appId = null;
            //var response = instance.GetListUpdates(releaseId, limit, offset, appKey, appId);
            //Assert.IsInstanceOf<RegulatoryListChanges> (response, "response is RegulatoryListChanges");
        }
        
    }

}
