/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace chemApiClient.Model
{
    /// <summary>
    /// Code
    /// </summary>
    [DataContract]
    public partial class Code : BaseDataType,  IEquatable<Code>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Code" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Code() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Code" /> class.
        /// </summary>
        /// <param name="DataType">DataType (required).</param>
        /// <param name="Name">Name (required).</param>
        /// <param name="Prompt">Prompt (required).</param>
        /// <param name="Value">Value (required).</param>
        /// <param name="_Code">_Code (required).</param>
        public Code(string DataType = null, string Name = null, string Prompt = null, string Value = null, string _Code = null)
        {
            // to ensure "DataType" is required (not null)
            if (DataType == null)
            {
                throw new InvalidDataException("DataType is a required property for Code and cannot be null");
            }
            else
            {
                this.DataType = DataType;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for Code and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Prompt" is required (not null)
            if (Prompt == null)
            {
                throw new InvalidDataException("Prompt is a required property for Code and cannot be null");
            }
            else
            {
                this.Prompt = Prompt;
            }
            // to ensure "Value" is required (not null)
            if (Value == null)
            {
                throw new InvalidDataException("Value is a required property for Code and cannot be null");
            }
            else
            {
                this.Value = Value;
            }
            // to ensure "_Code" is required (not null)
            if (_Code == null)
            {
                throw new InvalidDataException("_Code is a required property for Code and cannot be null");
            }
            else
            {
                this._Code = _Code;
            }
        }
        
        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name="data_type", EmitDefaultValue=false)]
        public string DataType { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets Prompt
        /// </summary>
        [DataMember(Name="prompt", EmitDefaultValue=false)]
        public string Prompt { get; set; }
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }
        /// <summary>
        /// Gets or Sets _Code
        /// </summary>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string _Code { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Code {\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  _Code: ").Append(_Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Code);
        }

        /// <summary>
        /// Returns true if Code instances are equal
        /// </summary>
        /// <param name="other">Instance of Code to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Code other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DataType == other.DataType ||
                    this.DataType != null &&
                    this.DataType.Equals(other.DataType)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Prompt == other.Prompt ||
                    this.Prompt != null &&
                    this.Prompt.Equals(other.Prompt)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                ) && 
                (
                    this._Code == other._Code ||
                    this._Code != null &&
                    this._Code.Equals(other._Code)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DataType != null)
                    hash = hash * 59 + this.DataType.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Prompt != null)
                    hash = hash * 59 + this.Prompt.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                if (this._Code != null)
                    hash = hash * 59 + this._Code.GetHashCode();
                return hash;
            }
        }
    }

}
