/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace chemApiClient.Model
{
    /// <summary>
    /// Inventory
    /// </summary>
    [DataContract]
    public partial class Inventory :  IEquatable<Inventory>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Inventory" /> class.
        /// </summary>
        /// <param name="RegulatoryList">RegulatoryList.</param>
        /// <param name="IsPresent">IsPresent (default to false).</param>
        /// <param name="Links">Links.</param>
        public Inventory(RegulatoryList RegulatoryList = null, bool? IsPresent = null, Links Links = null)
        {
            this.RegulatoryList = RegulatoryList;
            // use default value if no "IsPresent" provided
            if (IsPresent == null)
            {
                this.IsPresent = false;
            }
            else
            {
                this.IsPresent = IsPresent;
            }
            this.Links = Links;
        }
        
        /// <summary>
        /// Gets or Sets RegulatoryList
        /// </summary>
        [DataMember(Name="regulatory_list", EmitDefaultValue=false)]
        public RegulatoryList RegulatoryList { get; set; }
        /// <summary>
        /// Gets or Sets IsPresent
        /// </summary>
        [DataMember(Name="is_present", EmitDefaultValue=false)]
        public bool? IsPresent { get; set; }
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public Links Links { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Inventory {\n");
            sb.Append("  RegulatoryList: ").Append(RegulatoryList).Append("\n");
            sb.Append("  IsPresent: ").Append(IsPresent).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Inventory);
        }

        /// <summary>
        /// Returns true if Inventory instances are equal
        /// </summary>
        /// <param name="other">Instance of Inventory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Inventory other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RegulatoryList == other.RegulatoryList ||
                    this.RegulatoryList != null &&
                    this.RegulatoryList.Equals(other.RegulatoryList)
                ) && 
                (
                    this.IsPresent == other.IsPresent ||
                    this.IsPresent != null &&
                    this.IsPresent.Equals(other.IsPresent)
                ) && 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.Equals(other.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RegulatoryList != null)
                    hash = hash * 59 + this.RegulatoryList.GetHashCode();
                if (this.IsPresent != null)
                    hash = hash * 59 + this.IsPresent.GetHashCode();
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                return hash;
            }
        }
    }

}
