/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace chemApiClient.Model
{
    /// <summary>
    /// The chemical name for a specific substance_id
    /// </summary>
    [DataContract]
    public partial class SubstanceName :  IEquatable<SubstanceName>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubstanceName" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubstanceName() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubstanceName" /> class.
        /// </summary>
        /// <param name="Value">Value (required).</param>
        /// <param name="Iso6391Language">Iso6391Language (required).</param>
        /// <param name="Iso6391Code">Iso6391Code (required).</param>
        public SubstanceName(string Value = null, string Iso6391Language = null, string Iso6391Code = null)
        {
            // to ensure "Value" is required (not null)
            if (Value == null)
            {
                throw new InvalidDataException("Value is a required property for SubstanceName and cannot be null");
            }
            else
            {
                this.Value = Value;
            }
            // to ensure "Iso6391Language" is required (not null)
            if (Iso6391Language == null)
            {
                throw new InvalidDataException("Iso6391Language is a required property for SubstanceName and cannot be null");
            }
            else
            {
                this.Iso6391Language = Iso6391Language;
            }
            // to ensure "Iso6391Code" is required (not null)
            if (Iso6391Code == null)
            {
                throw new InvalidDataException("Iso6391Code is a required property for SubstanceName and cannot be null");
            }
            else
            {
                this.Iso6391Code = Iso6391Code;
            }
        }
        
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }
        /// <summary>
        /// Gets or Sets Iso6391Language
        /// </summary>
        [DataMember(Name="iso_639_1_language", EmitDefaultValue=false)]
        public string Iso6391Language { get; set; }
        /// <summary>
        /// Gets or Sets Iso6391Code
        /// </summary>
        [DataMember(Name="iso_639_1_code", EmitDefaultValue=false)]
        public string Iso6391Code { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubstanceName {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Iso6391Language: ").Append(Iso6391Language).Append("\n");
            sb.Append("  Iso6391Code: ").Append(Iso6391Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SubstanceName);
        }

        /// <summary>
        /// Returns true if SubstanceName instances are equal
        /// </summary>
        /// <param name="other">Instance of SubstanceName to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubstanceName other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                ) && 
                (
                    this.Iso6391Language == other.Iso6391Language ||
                    this.Iso6391Language != null &&
                    this.Iso6391Language.Equals(other.Iso6391Language)
                ) && 
                (
                    this.Iso6391Code == other.Iso6391Code ||
                    this.Iso6391Code != null &&
                    this.Iso6391Code.Equals(other.Iso6391Code)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                if (this.Iso6391Language != null)
                    hash = hash * 59 + this.Iso6391Language.GetHashCode();
                if (this.Iso6391Code != null)
                    hash = hash * 59 + this.Iso6391Code.GetHashCode();
                return hash;
            }
        }
    }

}
