/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace chemApiClient.Model
{
    /// <summary>
    /// Substances
    /// </summary>
    [DataContract]
    public partial class Substances :  IEquatable<Substances>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Substances" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Substances() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Substances" /> class.
        /// </summary>
        /// <param name="Substance">A collection of substance objects (required).</param>
        /// <param name="Links">Links.</param>
        public Substances(List<Substance> Substance = null, Links Links = null)
        {
            // to ensure "Substance" is required (not null)
            if (Substance == null)
            {
                throw new InvalidDataException("Substance is a required property for Substances and cannot be null");
            }
            else
            {
                this.Substance = Substance;
            }
            this.Links = Links;
        }
        
        /// <summary>
        /// A collection of substance objects
        /// </summary>
        /// <value>A collection of substance objects</value>
        [DataMember(Name="substance", EmitDefaultValue=false)]
        public List<Substance> Substance { get; set; }
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public Links Links { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Substances {\n");
            sb.Append("  Substance: ").Append(Substance).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Substances);
        }

        /// <summary>
        /// Returns true if Substances instances are equal
        /// </summary>
        /// <param name="other">Instance of Substances to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Substances other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Substance == other.Substance ||
                    this.Substance != null &&
                    this.Substance.SequenceEqual(other.Substance)
                ) && 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.Equals(other.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Substance != null)
                    hash = hash * 59 + this.Substance.GetHashCode();
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                return hash;
            }
        }
    }

}
