/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace chemApiClient.Model
{
    /// <summary>
    /// Contains information about the substance
    /// </summary>
    [DataContract]
    public partial class Substance :  IEquatable<Substance>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Substance" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Substance() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Substance" /> class.
        /// </summary>
        /// <param name="Id">Id (required).</param>
        /// <param name="PrimaryName">PrimaryName (required).</param>
        /// <param name="RegulatoryBurden">RegulatoryBurden.</param>
        /// <param name="Identifiers">Identifiers.</param>
        /// <param name="Names">Names.</param>
        /// <param name="RelatedSubstances">RelatedSubstances.</param>
        /// <param name="Links">Links.</param>
        public Substance(int? Id = null, string PrimaryName = null, float? RegulatoryBurden = null, Identifiers Identifiers = null, SubstanceNames Names = null, RelatedSubstances RelatedSubstances = null, Links Links = null)
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for Substance and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "PrimaryName" is required (not null)
            if (PrimaryName == null)
            {
                throw new InvalidDataException("PrimaryName is a required property for Substance and cannot be null");
            }
            else
            {
                this.PrimaryName = PrimaryName;
            }
            this.RegulatoryBurden = RegulatoryBurden;
            this.Identifiers = Identifiers;
            this.Names = Names;
            this.RelatedSubstances = RelatedSubstances;
            this.Links = Links;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="_id", EmitDefaultValue=false)]
        public int? Id { get; set; }
        /// <summary>
        /// Gets or Sets PrimaryName
        /// </summary>
        [DataMember(Name="primary_name", EmitDefaultValue=false)]
        public string PrimaryName { get; set; }
        /// <summary>
        /// Gets or Sets RegulatoryBurden
        /// </summary>
        [DataMember(Name="regulatory_burden", EmitDefaultValue=false)]
        public float? RegulatoryBurden { get; set; }
        /// <summary>
        /// Gets or Sets Identifiers
        /// </summary>
        [DataMember(Name="identifiers", EmitDefaultValue=false)]
        public Identifiers Identifiers { get; set; }
        /// <summary>
        /// Gets or Sets Names
        /// </summary>
        [DataMember(Name="names", EmitDefaultValue=false)]
        public SubstanceNames Names { get; set; }
        /// <summary>
        /// Gets or Sets RelatedSubstances
        /// </summary>
        [DataMember(Name="related_substances", EmitDefaultValue=false)]
        public RelatedSubstances RelatedSubstances { get; set; }
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public Links Links { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Substance {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PrimaryName: ").Append(PrimaryName).Append("\n");
            sb.Append("  RegulatoryBurden: ").Append(RegulatoryBurden).Append("\n");
            sb.Append("  Identifiers: ").Append(Identifiers).Append("\n");
            sb.Append("  Names: ").Append(Names).Append("\n");
            sb.Append("  RelatedSubstances: ").Append(RelatedSubstances).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Substance);
        }

        /// <summary>
        /// Returns true if Substance instances are equal
        /// </summary>
        /// <param name="other">Instance of Substance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Substance other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.PrimaryName == other.PrimaryName ||
                    this.PrimaryName != null &&
                    this.PrimaryName.Equals(other.PrimaryName)
                ) && 
                (
                    this.RegulatoryBurden == other.RegulatoryBurden ||
                    this.RegulatoryBurden != null &&
                    this.RegulatoryBurden.Equals(other.RegulatoryBurden)
                ) && 
                (
                    this.Identifiers == other.Identifiers ||
                    this.Identifiers != null &&
                    this.Identifiers.Equals(other.Identifiers)
                ) && 
                (
                    this.Names == other.Names ||
                    this.Names != null &&
                    this.Names.Equals(other.Names)
                ) && 
                (
                    this.RelatedSubstances == other.RelatedSubstances ||
                    this.RelatedSubstances != null &&
                    this.RelatedSubstances.Equals(other.RelatedSubstances)
                ) && 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.Equals(other.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.PrimaryName != null)
                    hash = hash * 59 + this.PrimaryName.GetHashCode();
                if (this.RegulatoryBurden != null)
                    hash = hash * 59 + this.RegulatoryBurden.GetHashCode();
                if (this.Identifiers != null)
                    hash = hash * 59 + this.Identifiers.GetHashCode();
                if (this.Names != null)
                    hash = hash * 59 + this.Names.GetHashCode();
                if (this.RelatedSubstances != null)
                    hash = hash * 59 + this.RelatedSubstances.GetHashCode();
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                return hash;
            }
        }
    }

}
