/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using chemApiClient.Client;
using chemApiClient.Model;

namespace chemApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUpdatesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id
        /// </summary>
        /// <remarks>
        /// Returns an **EntryChanges** collection. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>EntryChanges</returns>
        EntryChanges GetEntryUpdate (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null);

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id
        /// </summary>
        /// <remarks>
        /// Returns an **EntryChanges** collection. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>ApiResponse of EntryChanges</returns>
        ApiResponse<EntryChanges> GetEntryUpdateWithHttpInfo (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null);
        /// <summary>
        /// Get All List additions and removals released after release_id
        /// </summary>
        /// <remarks>
        /// Returns a **RegulatoryListChanges** object. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>RegulatoryListChanges</returns>
        RegulatoryListChanges GetListUpdates (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null);

        /// <summary>
        /// Get All List additions and removals released after release_id
        /// </summary>
        /// <remarks>
        /// Returns a **RegulatoryListChanges** object. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>ApiResponse of RegulatoryListChanges</returns>
        ApiResponse<RegulatoryListChanges> GetListUpdatesWithHttpInfo (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id
        /// </summary>
        /// <remarks>
        /// Returns an **EntryChanges** collection. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of EntryChanges</returns>
        System.Threading.Tasks.Task<EntryChanges> GetEntryUpdateAsync (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null);

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id
        /// </summary>
        /// <remarks>
        /// Returns an **EntryChanges** collection. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of ApiResponse (EntryChanges)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntryChanges>> GetEntryUpdateAsyncWithHttpInfo (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null);
        /// <summary>
        /// Get All List additions and removals released after release_id
        /// </summary>
        /// <remarks>
        /// Returns a **RegulatoryListChanges** object. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of RegulatoryListChanges</returns>
        System.Threading.Tasks.Task<RegulatoryListChanges> GetListUpdatesAsync (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null);

        /// <summary>
        /// Get All List additions and removals released after release_id
        /// </summary>
        /// <remarks>
        /// Returns a **RegulatoryListChanges** object. 
        /// </remarks>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of ApiResponse (RegulatoryListChanges)</returns>
        System.Threading.Tasks.Task<ApiResponse<RegulatoryListChanges>> GetListUpdatesAsyncWithHttpInfo (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UpdatesApi : IUpdatesApi
    {
        private chemApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UpdatesApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = chemApiClient.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UpdatesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = chemApiClient.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public chemApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id Returns an **EntryChanges** collection. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>EntryChanges</returns>
        public EntryChanges GetEntryUpdate (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
             ApiResponse<EntryChanges> localVarResponse = GetEntryUpdateWithHttpInfo(releaseId, substanceId, limit, offset, appKey, appId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id Returns an **EntryChanges** collection. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>ApiResponse of EntryChanges</returns>
        public ApiResponse< EntryChanges > GetEntryUpdateWithHttpInfo (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
            // verify the required parameter 'releaseId' is set
            if (releaseId == null)
                throw new ApiException(400, "Missing required parameter 'releaseId' when calling UpdatesApi->GetEntryUpdate");
            // verify the required parameter 'substanceId' is set
            if (substanceId == null)
                throw new ApiException(400, "Missing required parameter 'substanceId' when calling UpdatesApi->GetEntryUpdate");

            var localVarPath = "/updates_since/{release_id}/entry_changes/{substance_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (releaseId != null) localVarPathParams.Add("release_id", Configuration.ApiClient.ParameterToString(releaseId)); // path parameter
            if (substanceId != null) localVarPathParams.Add("substance_id", Configuration.ApiClient.ParameterToString(substanceId)); // path parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (appKey != null) localVarHeaderParams.Add("app_key", Configuration.ApiClient.ParameterToString(appKey)); // header parameter
            if (appId != null) localVarHeaderParams.Add("app_id", Configuration.ApiClient.ParameterToString(appId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryUpdate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EntryChanges>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EntryChanges) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EntryChanges)));
            
        }

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id Returns an **EntryChanges** collection. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of EntryChanges</returns>
        public async System.Threading.Tasks.Task<EntryChanges> GetEntryUpdateAsync (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
             ApiResponse<EntryChanges> localVarResponse = await GetEntryUpdateAsyncWithHttpInfo(releaseId, substanceId, limit, offset, appKey, appId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Specific Regulatory Data Updates that were released after release_id Returns an **EntryChanges** collection. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="substanceId">Substance ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of ApiResponse (EntryChanges)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EntryChanges>> GetEntryUpdateAsyncWithHttpInfo (string releaseId, string substanceId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
            // verify the required parameter 'releaseId' is set
            if (releaseId == null)
                throw new ApiException(400, "Missing required parameter 'releaseId' when calling UpdatesApi->GetEntryUpdate");
            // verify the required parameter 'substanceId' is set
            if (substanceId == null)
                throw new ApiException(400, "Missing required parameter 'substanceId' when calling UpdatesApi->GetEntryUpdate");

            var localVarPath = "/updates_since/{release_id}/entry_changes/{substance_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (releaseId != null) localVarPathParams.Add("release_id", Configuration.ApiClient.ParameterToString(releaseId)); // path parameter
            if (substanceId != null) localVarPathParams.Add("substance_id", Configuration.ApiClient.ParameterToString(substanceId)); // path parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (appKey != null) localVarHeaderParams.Add("app_key", Configuration.ApiClient.ParameterToString(appKey)); // header parameter
            if (appId != null) localVarHeaderParams.Add("app_id", Configuration.ApiClient.ParameterToString(appId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryUpdate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EntryChanges>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EntryChanges) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EntryChanges)));
            
        }

        /// <summary>
        /// Get All List additions and removals released after release_id Returns a **RegulatoryListChanges** object. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>RegulatoryListChanges</returns>
        public RegulatoryListChanges GetListUpdates (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
             ApiResponse<RegulatoryListChanges> localVarResponse = GetListUpdatesWithHttpInfo(releaseId, limit, offset, appKey, appId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get All List additions and removals released after release_id Returns a **RegulatoryListChanges** object. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>ApiResponse of RegulatoryListChanges</returns>
        public ApiResponse< RegulatoryListChanges > GetListUpdatesWithHttpInfo (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
            // verify the required parameter 'releaseId' is set
            if (releaseId == null)
                throw new ApiException(400, "Missing required parameter 'releaseId' when calling UpdatesApi->GetListUpdates");

            var localVarPath = "/updates_since/{release_id}/regulatory_list_changes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (releaseId != null) localVarPathParams.Add("release_id", Configuration.ApiClient.ParameterToString(releaseId)); // path parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (appKey != null) localVarHeaderParams.Add("app_key", Configuration.ApiClient.ParameterToString(appKey)); // header parameter
            if (appId != null) localVarHeaderParams.Add("app_id", Configuration.ApiClient.ParameterToString(appId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetListUpdates", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RegulatoryListChanges>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RegulatoryListChanges) Configuration.ApiClient.Deserialize(localVarResponse, typeof(RegulatoryListChanges)));
            
        }

        /// <summary>
        /// Get All List additions and removals released after release_id Returns a **RegulatoryListChanges** object. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of RegulatoryListChanges</returns>
        public async System.Threading.Tasks.Task<RegulatoryListChanges> GetListUpdatesAsync (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
             ApiResponse<RegulatoryListChanges> localVarResponse = await GetListUpdatesAsyncWithHttpInfo(releaseId, limit, offset, appKey, appId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get All List additions and removals released after release_id Returns a **RegulatoryListChanges** object. 
        /// </summary>
        /// <exception cref="chemApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">Release ID</param>
        /// <param name="limit">Number of items to retrieve (optional, default to 10)</param>
        /// <param name="offset">Offset of the first item returned (optional, default to 0)</param>
        /// <param name="appKey"> (optional)</param>
        /// <param name="appId"> (optional)</param>
        /// <returns>Task of ApiResponse (RegulatoryListChanges)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RegulatoryListChanges>> GetListUpdatesAsyncWithHttpInfo (string releaseId, int? limit = null, int? offset = null, string appKey = null, string appId = null)
        {
            // verify the required parameter 'releaseId' is set
            if (releaseId == null)
                throw new ApiException(400, "Missing required parameter 'releaseId' when calling UpdatesApi->GetListUpdates");

            var localVarPath = "/updates_since/{release_id}/regulatory_list_changes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (releaseId != null) localVarPathParams.Add("release_id", Configuration.ApiClient.ParameterToString(releaseId)); // path parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (appKey != null) localVarHeaderParams.Add("app_key", Configuration.ApiClient.ParameterToString(appKey)); // header parameter
            if (appId != null) localVarHeaderParams.Add("app_id", Configuration.ApiClient.ParameterToString(appId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetListUpdates", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RegulatoryListChanges>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RegulatoryListChanges) Configuration.ApiClient.Deserialize(localVarResponse, typeof(RegulatoryListChanges)));
            
        }

    }
}
