/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using chemApiClient.Api;
using chemApiClient.Model;
using chemApiClient.Client;
using System.Reflection;

namespace chemApiClient.Test
{
    /// <summary>
    ///  Class for testing Language
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LanguageTests
    {
        // TODO uncomment below to declare an instance variable for Language
        //private Language instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Language
            //instance = new Language();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Language
        /// </summary>
        [Test]
        public void LanguageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Language
            //Assert.IsInstanceOfType<Language> (instance, "variable 'instance' is a Language");
        }

        /// <summary>
        /// Test the property 'Iso6391Language'
        /// </summary>
        [Test]
        public void Iso6391LanguageTest()
        {
            // TODO unit test for the property 'Iso6391Language'
        }
        /// <summary>
        /// Test the property 'Iso6391Code'
        /// </summary>
        [Test]
        public void Iso6391CodeTest()
        {
            // TODO unit test for the property 'Iso6391Code'
        }

    }

}
