/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using chemApiClient.Api;
using chemApiClient.Model;
using chemApiClient.Client;
using System.Reflection;

namespace chemApiClient.Test
{
    /// <summary>
    ///  Class for testing Range
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RangeTests
    {
        // TODO uncomment below to declare an instance variable for Range
        //private Range instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Range
            //instance = new Range();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Range
        /// </summary>
        [Test]
        public void RangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Range
            //Assert.IsInstanceOfType<Range> (instance, "variable 'instance' is a Range");
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Test]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'LowerOp'
        /// </summary>
        [Test]
        public void LowerOpTest()
        {
            // TODO unit test for the property 'LowerOp'
        }
        /// <summary>
        /// Test the property 'LowerVal'
        /// </summary>
        [Test]
        public void LowerValTest()
        {
            // TODO unit test for the property 'LowerVal'
        }
        /// <summary>
        /// Test the property 'UpperOp'
        /// </summary>
        [Test]
        public void UpperOpTest()
        {
            // TODO unit test for the property 'UpperOp'
        }
        /// <summary>
        /// Test the property 'UpperVal'
        /// </summary>
        [Test]
        public void UpperValTest()
        {
            // TODO unit test for the property 'UpperVal'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'UnitType'
        /// </summary>
        [Test]
        public void UnitTypeTest()
        {
            // TODO unit test for the property 'UnitType'
        }

    }

}
