/* 
 * chemadvisor.io api
 *
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using chemApiClient.Api;
using chemApiClient.Model;
using chemApiClient.Client;
using System.Reflection;

namespace chemApiClient.Test
{
    /// <summary>
    ///  Class for testing RegulatoryList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegulatoryListTests
    {
        // TODO uncomment below to declare an instance variable for RegulatoryList
        //private RegulatoryList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegulatoryList
            //instance = new RegulatoryList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegulatoryList
        /// </summary>
        [Test]
        public void RegulatoryListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegulatoryList
            //Assert.IsInstanceOfType<RegulatoryList> (instance, "variable 'instance' is a RegulatoryList");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NavigatorLink'
        /// </summary>
        [Test]
        public void NavigatorLinkTest()
        {
            // TODO unit test for the property 'NavigatorLink'
        }
        /// <summary>
        /// Test the property 'SourceLink'
        /// </summary>
        [Test]
        public void SourceLinkTest()
        {
            // TODO unit test for the property 'SourceLink'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsInventory'
        /// </summary>
        [Test]
        public void IsInventoryTest()
        {
            // TODO unit test for the property 'IsInventory'
        }
        /// <summary>
        /// Test the property 'SourceLanguages'
        /// </summary>
        [Test]
        public void SourceLanguagesTest()
        {
            // TODO unit test for the property 'SourceLanguages'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Test]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
